FROM node:22.12.0 AS builder
WORKDIR /G-FLIX-TS
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /G-FLIX-TS/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
