version: "3.8"

services:
  frontend:
    build: ./Client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./App
    ports:
      - "3001:3000"
    env_file:
      - ./App/.env.development.local
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_back_end
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
