export const categoryFindMock = [
  {
    id: 1,
    name: 'Ação',
    createdAt: new Date(),
    updatedAt: new Date(),
    movies: [
      {
        id: 5,
        title: 'titulo2',
        url: 'url',
        cover: 'url',
        category_id: 1,
        youtube_id: 'dsadasda',
        createdAt: new Date(),
        updatedAt: new Date(),
        category: {
          id: 1,
          name: 'ação',
          createdAt: new Date(),
          updatedAt: new Date(),
          movies: [],
        },
        reactions: [],
        reactionCounts: 1,
        favorites: [],
        views: [
          {
            id: 1,
            id_user: 2,
            id_movie: 3,
            seconds_watched: 45,
            createdAt: new Date(),
            updated_at: new Date(),
            movie: {
              id: 3,
              title: 'titulo',
              url: 'url',
              cover: 'url',
              category_id: 1,
              youtube_id: 'dsadasda',
              createdAt: new Date(),
              updatedAt: new Date(),
              category: {
                id: 1,
                name: 'ação',
                createdAt: new Date(),
                updatedAt: new Date(),
                movies: [],
              },
              reactions: [],
              reactionCounts: 1,
              favorites: [],
              views: [],
            },
            user: {
              id: 2,
              name: 'guilherme',
              email: 'guilherme@.com',
              password: 'sasadas',
              type: 1,
              createdAt: new Date(),
              updatedAt: new Date(),
              reactions: [],
              favorites: [],
              views: [],
            },
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Terror',
    createdAt: new Date(),
    updatedAt: new Date(),
    movies: [
      {
        id: 4,
        title: 'titulo',
        url: 'url',
        cover: 'url',
        category_id: 1,
        youtube_id: 'dsadasda',
        createdAt: new Date(),
        updatedAt: new Date(),
        category: {
          id: 1,
          name: 'ação',
          createdAt: new Date(),
          updatedAt: new Date(),
          movies: [],
        },
        reactions: [],
        reactionCounts: 1,
        favorites: [],
        views: [
          {
            id: 1,
            id_user: 2,
            id_movie: 3,
            seconds_watched: 50,
            createdAt: new Date(),
            updated_at: new Date(),
            movie: {
              id: 3,
              title: 'titulo',
              url: 'url',
              cover: 'url',
              category_id: 1,
              youtube_id: 'dsadasda',
              createdAt: new Date(),
              updatedAt: new Date(),
              category: {
                id: 1,
                name: 'ação',
                createdAt: new Date(),
                updatedAt: new Date(),
                movies: [],
              },
              reactions: [],
              reactionCounts: 1,
              favorites: [],
              views: [],
            },
            user: {
              id: 2,
              name: 'guilherme',
              email: 'guilherme@.com',
              password: 'sasadas',
              type: 1,
              createdAt: new Date(),
              updatedAt: new Date(),
              reactions: [],
              favorites: [],
              views: [],
            },
          },
          {
            id: 1,
            id_user: 2,
            id_movie: 3,
            seconds_watched: 5,
            createdAt: new Date(),
            updated_at: new Date(),
            movie: {
              id: 3,
              title: 'titulo',
              url: 'url',
              cover: 'url',
              category_id: 1,
              youtube_id: 'dsadasda',
              createdAt: new Date(),
              updatedAt: new Date(),
              category: {
                id: 1,
                name: 'ação',
                createdAt: new Date(),
                updatedAt: new Date(),
                movies: [],
              },
              reactions: [],
              reactionCounts: 1,
              favorites: [],
              views: [],
            },
            user: {
              id: 2,
              name: 'guilherme',
              email: 'guilherme@.com',
              password: 'sasadas',
              type: 1,
              createdAt: new Date(),
              updatedAt: new Date(),
              reactions: [],
              favorites: [],
              views: [],
            },
          },
        ],
      },
    ],
  },
];

export const viewsPerCategoryMock = [
  {
    name: 'ação',
    movies: [
      {
        views: [
          {
            id: 1,
            id_user: 2,
            id_movie: 3,
            seconds_watched: 4,
            createdAt: new Date(),
            updated_at: new Date(),
          },
        ],
      },
    ],
  },
  {
    name: 'Aventura',
    movies: [
      {
        views: [
          {
            id: 1,
            id_user: 2,
            id_movie: 4,
            seconds_watched: 5,
            createdAt: new Date(),
            updated_at: new Date(),
          },
          {
            id: 1,
            id_user: 2,
            id_movie: 4,
            seconds_watched: 5,
            createdAt: new Date(),
            updated_at: new Date(),
          },
        ],
      },
    ],
  },
];
